version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  trading-service:
    build:
      context: ./trading-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq

  telegram-bot-service:
    build:
      context: ./telegram-bot-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq